spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gathy_itta?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1004
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profile:
    include: oauth
logging:
  level:
    org.hibernate.SQL: debug
